import js from '@eslint/js'
import reactHooks from 'eslint-plugin-react-hooks'
import tseslint from 'typescript-eslint'

/**
 * Lint configuration.
 *
 * Type-aware rather than syntax-only. The syntax-only rules catch typos that
 * the compiler already catches; the type-aware ones catch the class of bug
 * this codebase actually produces — a floating promise that silently drops a
 * database write, an `any` that lets an unvalidated model response through, a
 * condition that is always true because the value was never nullable.
 *
 * A few of the defaults are turned off deliberately, each with the reason.
 * Rules that are disabled without a reason accumulate until the lint step
 * means nothing.
 */
export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/.next/**',
      '**/dist/**',
      '**/drizzle/**',
      'data/**',
      'out/**',
      'docs/media/**',
      'packages/templates/fonts/**',
      // Generated by Next on every build.
      'apps/web/next-env.d.ts',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,

  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // A dropped promise here is a database write that never happened, or an
      // Instagram publish whose failure nobody sees. Error, not warning.
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': 'error',

      // `any` is how an unvalidated model response gets treated as trusted
      // data. Allowed only where it is written down why.
      '@typescript-eslint/no-explicit-any': 'error',

      // Unused variables are usually a half-finished edit. The underscore
      // prefix is the escape hatch for deliberately ignored bindings.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],

      // Template literals carrying an object print "[object Object]", which in
      // this codebase would usually be an error being logged uselessly.
      '@typescript-eslint/restrict-template-expressions': [
        'error',
        { allowNumber: true, allowBoolean: true },
      ],

      // Off: the schema and drizzle types produce a lot of legitimately
      // redundant-looking narrowing, and the rule's false positives there
      // would train everyone to add disable comments.
      '@typescript-eslint/no-unnecessary-condition': 'off',

      // Off: `error: unknown` in a catch is the correct shape, and this rule
      // objects to the necessary casts that follow.
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
    },
  },

  // React components.
  {
    files: ['apps/web/**/*.tsx'],
    plugins: { 'react-hooks': reactHooks },
    rules: {
      ...reactHooks.configs.recommended.rules,
    },
  },

  /*
    The control ADR 0001 (T5) says exists.

    That decision record states `dangerouslySetInnerHTML` is "banned in
    packages/templates — not discouraged, banned, enforced by lint". No such
    rule was ever configured. There are zero occurrences in the tree, so this
    was a missing control rather than a live bug — but a written-down control
    nobody implemented is worse than an unwritten one, because it is what the
    next reader checks instead of the code.

    Applied everywhere, not only to templates: the review page renders
    model-generated text, and the argument against inserting it as HTML is the
    same wherever it happens.

    `no-restricted-syntax` rather than `react/no-danger`, so this needs no extra
    plugin dependency. It catches the JSX attribute and the
    `createElement`-style property alike.
  */
  {
    files: ['**/*.ts', '**/*.tsx'],
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          selector: 'JSXAttribute[name.name="dangerouslySetInnerHTML"]',
          message:
            'dangerouslySetInnerHTML is banned (ADR 0001, T5). This product renders ' +
            'model-generated text; there is no case where inserting it as HTML is the ' +
            'right answer.',
        },
        {
          selector: 'Property[key.name="dangerouslySetInnerHTML"]',
          message:
            'dangerouslySetInnerHTML is banned (ADR 0001, T5). This product renders ' +
            'model-generated text; there is no case where inserting it as HTML is the ' +
            'right answer.',
        },
      ],
    },
  },

  // Scripts and tests are allowed to be blunter: they run once, by a person
  // watching the output, and a thrown error is a perfectly good result.
  {
    files: ['scripts/**/*.ts', '**/__tests__/**/*.ts', '**/*.test.ts'],
    rules: {
      '@typescript-eslint/no-non-null-assertion': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      // Test doubles must match the signature they stand in for, which is
      // often async even when the fake body has nothing to await.
      '@typescript-eslint/require-await': 'off',
    },
  },

  // Config files sit outside any tsconfig project, so type-aware rules have no
  // program to consult.
  {
    files: ['**/*.config.js', '**/*.config.mjs', '**/*.config.ts'],
    ...tseslint.configs.disableTypeChecked,
    rules: {
      ...tseslint.configs.disableTypeChecked.rules,
      // Next requires `headers()` to be async whether or not it awaits.
      '@typescript-eslint/require-await': 'off',
    },
  },
)
