import { and, desc, eq, lt, sql } from 'drizzle-orm'

import { withOrg, withoutTenantScope } from '../rls.ts'
import { assets, slides } from '../schema/index.ts'

/**
 * Tenant-scoped access to stored images.
 *
 * Two kinds live in one table: slides the renderer rasterised, and pictures a
 * person uploaded. They are the same object to everything downstream — an
 * immutable JPEG addressed by database id — so they share a table, a storage
 * layout and the anonymous serving route. `kind` exists so the picture library
 * can offer what a person may reuse without listing every slide ever rendered.
 *
 * Nothing here takes a path from a caller. A path is generated by
 * @claimfold/storage from the file's own content hash and only ever read back
 * out by id, which is what keeps the one unauthenticated route in the product
 * from becoming a file browser.
 */

export type AssetRow = typeof assets.$inferSelect

/**
 * Record an image that has already been written to storage.
 *
 * Idempotent, because the path contains the content hash: uploading the same
 * picture twice is the same row, not a duplicate. `onConflictDoNothing`
 * followed by a read is the same shape the publish worker uses for rendered
 * slides, and for the same reason — two requests can race on identical bytes.
 */
export async function recordAsset(
  orgId: string,
  input: {
    path: string
    sha256: string
    width: number
    height: number
    bytes: number
    kind: 'render' | 'upload'
  },
): Promise<AssetRow> {
  return withOrg(orgId, async (tx) => {
    const [inserted] = await tx
      .insert(assets)
      .values({ orgId, ...input })
      .onConflictDoNothing()
      .returning()

    if (inserted) return inserted

    const [existing] = await tx
      .select()
      .from(assets)
      .where(eq(assets.path, input.path))
      .limit(1)

    // Unreachable unless the conflicting row belongs to another tenant, which
    // cannot happen: the path is prefixed with this org's id.
    if (!existing) throw new Error('Asset conflicted on insert but could not be read back')
    return existing
  })
}

/** The picture library: uploads only, newest first. */
export async function listUploads(orgId: string, limit = 60): Promise<AssetRow[]> {
  return withOrg(orgId, async (tx) => {
    return tx
      .select()
      .from(assets)
      .where(eq(assets.kind, 'upload'))
      .orderBy(desc(assets.createdAt))
      .limit(limit)
  })
}

/**
 * The picture library, plus whatever this post's slides already use.
 *
 * `listUploads` caps at the 60 newest, which is right for a browsing gallery
 * and wrong as the editor's only source of truth. The slide editor built its
 * image radio group from that list alone, so once a post's own picture aged out
 * of the window:
 *
 *  - the preview went blank, because the path could not be resolved; and
 *  - no radio was `defaultChecked`, so the browser submitted no `imageAssetId`
 *    at all, `readSlideContentForm` dropped the key, and `updateSlide` replaced
 *    the whole `content` jsonb — fixing a typo silently deleted the photograph.
 *
 * The second one is data loss with no warning and no undo, which makes this a
 * query problem rather than a component problem: the editor must be handed
 * every asset it needs to represent, not just the recent ones.
 */
export async function listUploadsForPost(
  orgId: string,
  postId: string,
  limit = 60,
): Promise<AssetRow[]> {
  return withOrg(orgId, async (tx) => {
    const recent = await tx
      .select()
      .from(assets)
      .where(eq(assets.kind, 'upload'))
      .orderBy(desc(assets.createdAt))
      .limit(limit)

    const seen = new Set(recent.map((row) => row.id))

    const inUse = await tx
      .select()
      .from(assets)
      .where(
        and(
          eq(assets.kind, 'upload'),
          sql`exists (
            select 1 from ${slides} s
            where s.post_id = ${postId}
              and s.content->>'imageAssetId' = ${assets.id}::text
          )`,
        ),
      )

    // In-use pictures appended rather than merged by date: the gallery stays
    // "newest first" and the extras are clearly the ones this post already uses.
    return [...recent, ...inUse.filter((row) => !seen.has(row.id))]
  })
}

/**
 * Every asset id currently referenced by a slide in this org.
 *
 * `imageAssetId` lives inside the `slides.content` jsonb rather than in a
 * column, so no foreign key protects it and this has to be asked explicitly.
 * That jsonb-hidden reference is the reason the caller's own reuse check was
 * written in application code — and got it wrong.
 */
async function referencedAssetIds(
  tx: Parameters<Parameters<typeof withOrg>[1]>[0],
  excludeSlideId?: string,
): Promise<Set<string>> {
  const rows = await tx
    .select({ id: sql<string>`${slides.content}->>'imageAssetId'` })
    .from(slides)
    .where(
      and(
        sql`${slides.content}->>'imageAssetId' is not null`,
        excludeSlideId ? sql`${slides.id} <> ${excludeSlideId}` : undefined,
      ),
    )

  return new Set(rows.map((r) => r.id).filter(Boolean))
}

/**
 * Forget an upload, returning its path so the caller can delete the file.
 *
 * Two steps rather than one because this package does not touch the disk —
 * @claimfold/storage owns that, and a repository that reached into the
 * filesystem would be a second place to get the containment check wrong.
 *
 * Only ever removes an upload. Rendered slides are cache entries the publish
 * worker recreates on demand and are addressed by content hash, so deleting one
 * out from under a scheduled post would be a way to break publishing.
 *
 * Refuses when any slide in the org still points at it, and does the check in
 * the same transaction as the delete. Storage is content-addressed, so the same
 * photo used on two posts is literally one row: the caller previously checked
 * only the slides of the post it happened to be editing, which meant removing a
 * picture on post B silently blanked it on post A and unlinked the file out
 * from under it. `excludeSlideId` is the slide being edited right now, whose
 * own reference is about to be replaced.
 *
 * @returns the stored path when the row was deleted, or null when it was kept
 *          (still referenced, absent, or not an upload).
 */
export async function forgetUpload(
  orgId: string,
  assetId: string,
  excludeSlideId?: string,
): Promise<string | null> {
  return withOrg(orgId, async (tx) => {
    const stillUsed = await referencedAssetIds(tx, excludeSlideId)
    if (stillUsed.has(assetId)) return null

    const [row] = await tx
      .delete(assets)
      .where(and(eq(assets.id, assetId), eq(assets.kind, 'upload')))
      .returning({ path: assets.path })

    return row?.path ?? null
  })
}

/**
 * Rendered images no slide points at any more, past the retention window.
 *
 * Nothing deleted these. `updateSlideCopy` nulls `renderHash`/`assetId` on every
 * copy edit and the next publish writes a fresh content-hashed JPEG plus a new
 * row, so an install leaked one file and one row per slide per edit, forever.
 *
 * The delay matters: a render orphaned seconds ago may belong to a publish
 * currently in flight. Anything older than the window is genuinely unreachable.
 *
 * Unscoped because retention is a cross-tenant sweep with no tenant in context.
 * It reads two columns and never returns content.
 */
export async function findOrphanedRenderAssets(
  olderThanMs: number,
  limit = 500,
): Promise<{ id: string; path: string }[]> {
  const cutoff = new Date(Date.now() - olderThanMs)

  return withoutTenantScope(async (tx) =>
    tx
      .select({ id: assets.id, path: assets.path })
      .from(assets)
      .where(
        and(
          eq(assets.kind, 'render'),
          lt(assets.createdAt, cutoff),
          sql`not exists (select 1 from ${slides} s where s.asset_id = ${assets.id})`,
          sql`not exists (select 1 from ${slides} s where s.content->>'imageAssetId' = ${assets.id}::text)`,
        ),
      )
      .limit(limit),
  )
}

/** Drop asset rows by id. Paired with `findOrphanedRenderAssets`. */
export async function deleteAssetRows(ids: string[]): Promise<number> {
  if (ids.length === 0) return 0

  return withoutTenantScope(async (tx) => {
    const removed = await tx
      .delete(assets)
      .where(sql`${assets.id} in ${ids}`)
      .returning({ id: assets.id })

    return removed.length
  })
}
