import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { describe, expect, it } from 'vitest'

import { collectFacts } from '../../../../scripts/public-facts.ts'

/**
 * The figures the marketing site quotes have to match this repository.
 *
 * The site lives in its own repository, so nothing stopped a limit from
 * moving here while the page went on stating the old one. That is a bad
 * failure for a product whose argument is about not saying things that are
 * not so, and it is invisible: no build breaks, the page just becomes
 * quietly wrong.
 *
 * `docs/public-facts.json` is the published set, generated by `npm run
 * facts`. This test regenerates it from source and fails if the committed
 * copy has drifted, so moving a constant without republishing is caught
 * here rather than by a reader.
 */

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '../../../..')

describe('published facts', () => {
  const committed = JSON.parse(
    readFileSync(resolve(repoRoot, 'docs/public-facts.json'), 'utf8'),
  ) as Record<string, unknown>

  it('match what the source says today', () => {
    expect(committed).toEqual(collectFacts())
  })

  it('still describe a gate that refuses something', () => {
    // A guard on the guard: if these ever read as "no limit", the file is
    // being generated from something that stopped being the gate.
    expect(committed['slidesMin']).toBeGreaterThan(0)
    expect(committed['slidesMax']).toBeGreaterThan(committed['slidesMin'] as number)
    expect(committed['confidenceFloorMinimum']).toBeGreaterThan(0)
    expect(committed['maxCaptionCharacters']).toBeGreaterThan(0)
  })
})
